### ISSUE TITLE
Missing option to delete polygon filter

### ISSUE THREAD

**Issue by B-Hartmann** [DC-analysis/DCscope#100]
The option to delete a polygon filter is missing, which is unfortunate if you miss-clicked and accidentally created a new one. Would be nice to have a third button in the polygon filter menu in the quick view window to delete it..

**Comment by paulmueller** [comment]
It should only be possible to delete a polygon filter if it is not part of a filter ray.

**Comment by B-Hartmann** [comment]
I just realized by trying out that unused polygon filters are not saved when you use the option "Save Session". I created a new polygon filter, selected it in a filter, clicked apply, then deselected the polygon filter, clicked apply again, saved the session, closed Shape-Out2, started it again, loaded the session, and it was not there.

**Comment by paulmueller** [comment]
OK, that makes sense to me. Does it make sense to you? (At least it's a workaround for now) I think an option to delete a polygon filter might still improve the user experience.

**Comment by B-Hartmann** [comment]
It is a workaround for now, yes.
But I sometimes activate or deactivate filters when analyzing the data, and when I save a session, I expect that all the filters and plots that I created are saved, even the unused ones.

**Comment by paulmueller** [comment]
I created a new issue for the session-saving: https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/issues/101

**Comment by paulmueller** [comment]
Note that with the current design it is not straight-forward to check whether a polygon filter may be deleted (if it is part of a filter ray). So instead, Shape-Out will just trust the user to know what he is doing.
