### ISSUE TITLE
Terminal-like window opens and stays open when starting Shape-Out

### ISSUE THREAD

**Issue by B-Hartmann** [DC-analysis/DCscope#102]
Windows 10 version 2004
Shape-Out2 2.7.2

When starting Shape-Out 2.7.2, a black window that looks like the Windows cmd.exe opens up and stays open. If you close it, Shape-Out gets closed too. 
It's just another window, and you can minimize it, so there is no real problem here, it would just be nice and tidy if it wouldn't stay open.

![shape_out_2-7-2_black_window](https://user-images.githubusercontent.com/75362246/132643808-ee4b251f-cad8-4813-b36f-1e9e755be8ab.PNG)

**Comment by paulmueller** [comment]
Sorry, I added this to debug #98
