### ISSUE TITLE
Young's Modulus computation: Displaying wrong unit when manually setting the viscosity

### ISSUE THREAD

**Issue by felix-r** [DC-analysis/DCscope#104]
I just wanted to compute some Young's moduli in ShapeOut 2 under "Bulk action -> Young's modulus ..." by manually setting the viscosity and got unrealistic values and I'm sure this is because the interface asks for values in Pa s while the computation is then done with this value in mPa s. Here an screenshot how the interface looks like:
![image](https://user-images.githubusercontent.com/19806005/139055616-853b0765-224e-4eb5-896a-96d6fafaeecf.png)

it should be `mPa s` not `Pa s`.

**Comment by paulmueller** [comment]
Yes, viscosity is in [mPas]. Thanks for spotting this.
