### ISSUE TITLE
Compute Statistical Significance not available on macOS

### ISSUE THREAD

**Issue by Eisstand** [DC-analysis/DCscope#105]
Hi, 

I am running ShapeOut 2.8.0 with R 4.1.1 on macOS Catalina (10.15) and the option to calculate statistical significance under Compute is missing. Under Preferences the R/Ime4 Tab can be clicked but all options are greyed out and not editable. What am I doing wrong?

![image](https://user-images.githubusercontent.com/69454062/139267316-f7382ce8-4153-45f2-9e2a-7fe0f1bd6b49.png)

**Comment by paulmueller** [comment]
On macOS, this is not working if you have installed Shapw-Out via installer. If you would like to have that option on macOS, you have to install Shape-Out as a Python package via `pip install shapeout2`. See also https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/issues/73
