### ISSUE TITLE
Plugin features/extensions do not show up initially in list of features when exporting statistics

### ISSUE THREAD

**Issue by B-Hartmann** [DC-analysis/DCscope#117]
Shape-Out 2.9.4
Windows 10

When I have a dataset and some filters and want to compute statistics, the list of features doesn't show my extensions/plugin features. I have to open the preferences once (not even opening the tab "Extensions") and then go to "export statistics" again to see all features and be able to select them.
It's like Shape-Out forgot that I added the extensions and needs a reminder first...

**Comment by paulmueller** [comment]
I cannot reproduce it with 2.9.5 on Ubuntu using the fluorescence density example plugin feature from https://shapeout2.readthedocs.io/en/stable/sec_qg_extensions.html#example-fluorescence-volume. Could you please try again?

**Comment by B-Hartmann** [comment]
Shape-Out 2.9.5 doesn't fix the issue.
I cannot see the added features anywhere, not in the drop-down menus in the quickview, not in the drop-down menus in plot settings, not in the list for calculating statistics.
I need to open the preferences first and close it agian, then select a dataset again in the quickview and closing and re-opening the analysis view to update all the drop-down menus.

EDIT:
I can confirm this behavior on another machine running Windows 10 and Shape-Out 2.9.4 and also Shape-Out 2.9.5.

**Comment by B-Hartmann** [comment]
Btw, in the first blue info box on the documentation website you linked above, it says _If you installed Shape-In via installer (not via pip), then many extensions might not work ...._  
Is it correct that it says Shape-In here? Should it not be Shape-Out?

**Comment by paulmueller** [comment]
This is a bug that only affects Windows (`QStandardPaths.AppLocalDataLocation` vs `QStandardPaths.AppDataLocation`). Shape-Out stores the extensions in your roaming user directory (which is correct), but on startup only checks in the local user directory.
