### ISSUE TITLE
Filtering for one "Most probable ML class" not possible with one box filter

### ISSUE THREAD

**Issue by B-Hartmann** [DC-analysis/DCscope#123]
ShapeOut 2.11.0

When using a box filter to only get events with the same "most probable ml class", let's say, ml_class = 4, I run into the following problem:
The box filter for that feature only allows integer values, and when I filter with min=4 and max=4, the filter does not work at all, but if I filter with min=3 and max=4, both classes, 3 and 4, are selected, although I only want ml_class = 4. 

The current workaround is to use two filters, one with min=3 and max=4 and the other one with min=4 and max=5.
I think it would be nice if the box filter would work by setting min and max value of the filter to the same value (4 in my example).

**Comment by paulmueller** [comment]
OK, on second thought this might be more complicated. If you define a box filter for integer features, you usually always have the boundaries included. This behavior would change if we fixed this issue (which is bad).

One option would be to make the sliders work with floating point values (e.g. including 0.5 steps). Then the user can fine-grain.

**Comment by B-Hartmann** [comment]
I am not sure I can follow your thoughts. If the boundaries were included, that would be exactly what I wanted. Why would the behavior change if the bug was fixed?

**Comment by paulmueller** [comment]
If you set min=3 and max=4 and you get both classes, then the boundaries (min and max) are included. My initial thought was that one of the boundaries should not be included (so you only get one class), but that might break other pipelines.
