### ISSUE TITLE
ML filter in ShapeOut2 doesn't work for a single class

### ISSUE THREAD

**Issue by marketakub** [DC-analysis/DCscope#128]
I would like to filter a single class according to the "most probably ML class". This doesn't work, it works only if I choose at least 2 classes (e.g. range 3-4).

**Comment by paulmueller** [comment]
Is this a duplicate of https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/issues/123 or is this something new?

**Comment by marketakub** [comment]
Seems like a duplicate

**Comment by marketakub** [comment]
Closing
