### ISSUE TITLE
Box filter spin box selection is frustrating

### ISSUE THREAD

**Issue by paulmueller** [DC-analysis/DCscope#149]
When editing box filter spin boxes, changing the values can be frustrating:

- when deleting a character after the decimal point, a zero is inserted at the end and it is not possible to insert a new character
- when removing the characters before the decimal point and then pressing "1", "10" is shown before the decimal point

This requires editing the custom logic around these spin boxes which should be straight forward.

**Comment by B-Hartmann** [comment]
If I am not mistaken, this is what I described in #135

**Comment by paulmueller** [comment]
Right. And I actually implemented what I suggested back then :+1:
