### ISSUE TITLE
Export Data - use only datasets checked as 'use this dataset'

### ISSUE THREAD

**Issue by chrherold** [DC-analysis/DCscope#15]
When exporting data, all datasets present in a session are exported. It would be preferable if only those datasets were exported that are checked as 'use this dataset' in the Block Matrix at the moment of the export.

**Comment by paulmueller** [comment]
I suppose this also applies to computed statistics.

**Comment by chrherold** [comment]
Yes. This way one can easily create a set of data of specific interest without completely changing a session.
