### ISSUE TITLE
Statistics under 'Quick View' in Shape-Out 2.15.0 doesn't update 

### ISSUE THREAD

**Issue by rgoswam1** [DC-analysis/DCscope#154]
By default, the measurements show Area vs Deformation plot and the related statistics under the 'Quick View' tab. However, when loading a new measurement as shown in image **Capture_01** (Measurement no. 4 (0.16 µl/s flow rate)) and potting the Area vs Young's modulus [kPa], the plot is updated but the statistics are not.
![Capture_01](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/assets/156325027/a55dd742-37d8-4861-8ca6-2453794a52ab)

**Capture_02** shows that the parameters under 'Plot' were selected as Area vs. Young's modulus [kPa], and then the measurement (no. 5 (0.2 µl/s)) was loaded. In this case, the statistics are updated.
![Capture_02](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/assets/156325027/f6fd261b-2399-4522-b4b6-e782bf1e2742)

**Capture_03** shows, for the same measurement (no. 5 (0.2 µl/s)), if the plotting parameters are changed from Area vs Young's modulus [kPa] to Area vs Deformation, the plot is updated but the statistics are not.
![Capture_03](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/assets/156325027/2816e0e1-e239-4d47-97ac-524297010878)

**Comment by paulmueller** [comment]
Thanks, I missed this when introducing caching for the statistics in 2.15.0.

**Comment by paulmueller** [comment]
The features used for plotting were not part of the cache key. This will be fixed in 0.15.1.
