### ISSUE TITLE
Shape-Out adds prefix "so2exp" to every log entry when exporting data, but does not create dedicated log entry

### ISSUE THREAD

**Issue by B-Hartmann** [DC-analysis/DCscope#157]
Shape-Out 2.15.1
Windows 10

I filtered and exported a file and noticed in the logs (using DCKit 0.16.0) that a string "so2exp" is added to the title of all existing log entries. 
I do not think this is intended and it does not make sense to me, I would expect that Shape-Out creates a log entry for the export.
And if the exported file is exported by Shape-Out again, it will add this prefix again 

![image](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/assets/75362246/b648dffb-230f-42d8-b4d4-ebfdac6d37af)
After second export:
![image](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/assets/75362246/906fea20-b43d-4812-bb5e-672a828cc050)

**Comment by paulmueller** [comment]
Thanks. The idea of the prefix is to make apparent that the data file is not an original measurement file. I agree that adding an export log would be a better way to convey that.

Just for context: Adding a prefix to the logs is mainly important when joining .rtdc files.

**Comment by B-Hartmann** [comment]
Yes, a separate entry would be more consistent with the style of logs in RTDC files (every action that changes the file creates a new entry in the logs).

I checked how the logs look like for the case of joining two datasets after exporting:
![logs_after_exporting_and_joining_datasets](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/assets/75362246/e81571a2-ae48-4ee3-9f4b-8c42c34c5e58)

I like how the logs from the source files have the prefix "src-#1" and so on, it allows users to quickly identify which entry belongs to which source file. I recommend that the entries "cfg_src-#1" are named in the same fashion, e.g. "src-#1_cfg" to be consistent and to have all logs related to the same source file together in the list of logs.

Would it make sense to have an entry called "file history", in which all other entries are listed together with a time stamp so that one can see what has happened to the file in chronological order, especially in files which were processed many times? Theoretically, this information is in the file, but spread out over all log entries and the metadata section of the file (entries "shapein-acquisition" and "SoftwareSettings" do not contain a time stamp, but the creation time of the file is in the metadata section). (Actually, after joining, the time and date of acquisition can be found in "cfg_src-#1".)

I mean something like
```
2024-02-08 14:12:13 - src-#1_shapein_acquisition
2024-02-08 14:12:13 - src-#1_M005_SoftwareSettings.ini
2024-02-08 16:15:13 - src-#2_shapein_acquisition
2024-02-08 16:15:13 - src-#2_M006_SoftwareSettings.ini
2024-02-14 07:02:21 - dclab-join
```

**Comment by paulmueller** [comment]
I have created https://github.com/DC-analysis/dclab/issues/251 to reflect your point on having a separate log entry for every export.

**Comment by paulmueller** [comment]
I have created https://github.com/DC-analysis/dclab/issues/252 for your request to have something like a time trace on the logs.
