### ISSUE TITLE
ref: migrate from PyQt5 to PyQt6

### ISSUE THREAD

**Issue by paulmueller** [DC-analysis/DCscope#165]
The latest version of QtCreator does not support PyQt5 (the resulting .ui files cannot be used due to additional type definitions).
Therefore, it would be good to migrate the codebase and all .ui files to PyQt6.
For the differences between the two and some technical details for the migration, see e.g. https://www.pythonguis.com/faq/pyqt5-vs-pyqt6/

**Comment by RaghavaAlajangi** [comment]
Hi @paulmueller 
So, basically, it is all about replacing components mentioned in the link you provided, right? Or do we need to run the app with PyQt6 and check where it is throwing errors?

**Comment by paulmueller** [comment]
Yes. To be clear, it means
1. opening all .ui files with the latest version of QtCreator and saving it back (Qt6 automatically adds type hints and maybe other things)
2. in pyqt6, several imports and attributes are different and need to be imported from other locations in pyqt6 compared to where they were before in pyqt5 (the link above is only an example, there are probably better resources for migrating pyqt5 code to pyqt6)

**Comment by paulmueller** [comment]
Current road block: https://forum.qt.io/topic/158135/new-update-of-qt-creator-causes-problem-with-pyqt6-uic/4

The `pyuic6` program cannot convert the .ui files created by QtCreator 14.0.2. The only sensible solutions here are (a) to wait for a fix or (b) use QtCreator 8 instead.

**Comment by paulmueller** [comment]
Running `python -m shapeout2 --version` still causes a segmentation fault.

**Comment by paulmueller** [comment]
Everything is currently sitting in the `pyqt6` branch.

**Comment by paulmueller** [comment]
Segmentation fault is fixed with ad8eaf5

**Comment by paulmueller** [comment]
I managed to make everything work, but we are currently restricted to using QtCreator 8.

**Comment by paulmueller** [comment]
done in #177
