### ISSUE TITLE
Load Session - Box filter deselection lost

### ISSUE THREAD

**Issue by chrherold** [DC-analysis/DCscope#19]
If a session is loaded the Boxfilters of 'area' Brightness average' and 'Deformation' are included as chosen even though they were deselected in the Session that was saved.

**Comment by chrherold** [comment]
Same thing happens on filter import

**Comment by paulmueller** [comment]
The problem was that these filters were set active by default in *any* case. I disabled this. By default, now no box filters are set and the user has to choose them explicitly. I think this is the better anyways. I think I just put them there for quick testing...
