### ISSUE TITLE
Statistics output - All datasets in session - Name and Slot incorrect

### ISSUE THREAD

**Issue by chrherold** [DC-analysis/DCscope#23]
I just tried to compute the statistics for the following six datasets

![image](https://user-images.githubusercontent.com/13899168/70147530-b9732480-16a4-11ea-8e00-2534fafec14e.png)

and got strange entries in the .tsv

<img width="543" alt="image" src="https://user-images.githubusercontent.com/13899168/70147611-ec1d1d00-16a4-11ea-9d3b-1047c669ac26.png">

**Comment by paulmueller** [comment]
LOL, sorry!
