### ISSUE TITLE
OSX inferface specific - update view of Block Matrix after first Plot added

### ISSUE THREAD

**Issue by chrherold** [DC-analysis/DCscope#28]
OSX version:

When a plot is added for the first time in a session, the plot column in the Block Matrix does not readily appear. Selecting a different program or rescaling the Block Matrix window leads to correct rebuilding of the Block Matrix. 

Behavior for further plots added is as expected.

**Comment by paulmueller** [comment]
I tried to fix it in 58c9cce. Please check again in 2.0.0b5.

**Comment by chrherold** [comment]
Unfortunately, still the same behavior.

**Comment by paulmueller** [comment]
Please check again in 2.0.0b6.

**Comment by paulmueller** [comment]
Please check again in 2.0.0b10.

**Comment by chrherold** [comment]
No change in b10 either.

**Comment by paulmueller** [comment]
I cannot reproduce this on my macOS test machine. However. I run macOS 10.11.6 and are forced to use PyQt5 5.9...
Is this still an issue for you with b11?

**Comment by chrherold** [comment]
Seems to have disappeared with b11! Nice, do you know why?

**Comment by paulmueller** [comment]
No
