### ISSUE TITLE
OSX interface - disable independent 'close window' buttons in header of windows

### ISSUE THREAD

**Issue by chrherold** [DC-analysis/DCscope#29]
In OSX, the 'close' button in the header of windows like Plot, Analysis View and Quick View is active and can be used to close a window (red button). 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/13899168/70613964-e32ecd00-1c09-11ea-9f3d-cb76a66daf70.png">

This leads to loss of content when the window is opened again. Windows are only gray.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/13899168/70614299-897ad280-1c0a-11ea-8eb5-c57c4891a011.png">

I would suggest disabling the 'close' button.

**Comment by paulmueller** [comment]
I tried to fix it in f169ab5. Let me know if this still persists in 2.0.0b5.

**Comment by paulmueller** [comment]
This should have done the trick: 034ebb4

https://stackoverflow.com/questions/49477346/remove-disable-close-button-in-pyqt5

**Comment by chrherold** [comment]
Close buttons are still alive and kicking in 2.0.0b7. :/

**Comment by paulmueller** [comment]
What about 2.0.0b8? Could you please check all windows (QuickView, AnalysisView and plots)?

**Comment by chrherold** [comment]
same issue ... for all three window types

**Comment by paulmueller** [comment]
b9? https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/releases/tag/2.0.0b9

**Comment by paulmueller** [comment]
Note that in b9, not all windows do have the title set. I used different windowFlags on each of them. If you cannot close one of them, please let me know.

**Comment by chrherold** [comment]
3x no. Sorry :/

Running OSX 10.14.6 btw
