### ISSUE TITLE
Version Check (in Windows)

### ISSUE THREAD

**Issue by chrherold** [DC-analysis/DCscope#30]
When opening the program a 'new version available' window appears suggesting the just installed version:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/13899168/70615409-a44e4680-1c0c-11ea-8c09-23211d1bcfb9.png">

**Comment by paulmueller** [comment]
I did that actually just for testing and forgot to remove it. It probably means that version checking does not work on macOS. Let's see.
