### ISSUE TITLE
QuickView - incorrect alignment and unwanted window rescaling

### ISSUE THREAD

**Issue by chrherold** [DC-analysis/DCscope#31]
(Both Windows and Osx)

If the Plot section of the QuickView ~Analysis View~ is opened the elements are misaligned

<img width="726" alt="image" src="https://user-images.githubusercontent.com/13899168/70615845-7289af80-1c0d-11ea-9ca9-b29f854e2102.png">

Furthermore, when staying in this section and moving the window around or trying to rescale the window, it continuously expands in width for the time the window is clicked on.

Behavior in Event and Polygon Filter mode is correct. In these modes also the unwanted rescaling disappears but immediately reappears when changing back to Plot.

**Comment by paulmueller** [comment]
I think I fixed it in e833ebc. Please reopen if the problem persists in 2.0.0b5.

**Comment by chrherold** [comment]
The problem still persists in 2.0.0b5. Behavior is unchanged.

**Comment by paulmueller** [comment]
I just updated my PyQt5 version and can reproduce it.
