### ISSUE TITLE
Force subplots to have the same aspect ratio

### ISSUE THREAD

**Issue by paulmueller** [DC-analysis/DCscope#33]
The aspect ratio is currently determined somehow by pyqtgraph taking the available space into account.

Pyqtgraph currently does not seem to have a feature that allows to make all plots the same size (such that if you overlay the plots, all axes and ticks would coincide).

**Comment by chrherold** [comment]
one comment on that: subplot size seems to depend on the plot title

<img width="916" alt="image" src="https://user-images.githubusercontent.com/13899168/72991472-58d5ad80-3df2-11ea-9f14-82323f827eac.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/13899168/72991576-8589c500-3df2-11ea-9fd9-9549898d899d.png">


<img width="916" alt="image" src="https://user-images.githubusercontent.com/13899168/72991513-69862380-3df2-11ea-986e-d1571fd1a6a6.png">

**Comment by paulmueller** [comment]
yeah thanks, saw that too :roll_eyes:

**Comment by paulmueller** [comment]
Currently we are using `pg.GraphicsLayoutWidget`. Maybe we should use [QGraphicsGridLayout](https://doc.qt.io/qt-5/qgraphicsgridlayout.html#details) - maybe with [setColumnFixedWidth](https://doc.qt.io/qt-5/qgraphicsgridlayout.html#setColumnFixedWidth).

**Comment by paulmueller** [comment]
Workaround is to create an empty title label and anchor another label to it, see 616b71b.
See https://ci.appveyor.com/project/paulmueller/shapeout2/builds/37925366/artifacts for a preview.
