### ISSUE TITLE
Cannot set filter ranges

### ISSUE THREAD

**Issue by felix-r** [DC-analysis/DCscope#34]
I just updated to version b11 and now I cannot set the range of the box filters anymore. I can check the boxes but not edit the values.

![image](https://user-images.githubusercontent.com/19806005/72336772-b31f9180-36c1-11ea-8675-671762c3d5a3.png)

**Comment by paulmueller** [comment]
In the screenshot you are in the "box filter selection" mode. You have to hit "...Finish editing" before you can use the filters. Does the button work? If it's that, I guess it would make sense to highlight it in a different color or so.

**Comment by felix-r** [comment]
Alright. That worked. Still have to get used to the new interface.

**Comment by chrherold** [comment]
Paul was faster. :)

Yes either color, or we make a change to the optics on the filter selection mode and make numbers and bars invisible but give pictograms of the individual features instead. We pictograms in Shape-In. Although, inertia ratio will pose quite some challenge. 

<img width="157" alt="image" src="https://user-images.githubusercontent.com/13899168/72337549-0cd48b80-36c3-11ea-8f9d-87b23d169bac.png">

**Comment by paulmueller** [comment]
@chrherold Regarding pictograms: It might make sense, but as you said we don't have pictograms for all features. Please open a new issue if you think we should follow up on that.
