### ISSUE TITLE
Image process

### ISSUE THREAD

**Issue by liang-minhui** [DC-analysis/DCscope#42]
Hi all,
this is a beginner, I wonder if ShapeOut includes image processing? Or it's for processing the processed image data? and may I know which image processing code it uses,is it open source?

Appreciate any reply!
Liang

**Comment by paulmueller** [comment]
I believe the documentation will answer your question: https://shapeout2.readthedocs.io/en/stable/

Shape-Out is a user interface for data analysis in real-time deformability cytometry (RT-DC). It is not a general-purpose image processing platform...

**Comment by liang-minhui** [comment]
May I ask some more questions?
If the image processing is done by Shape-In? Where can I download and install Shape-in?

Thank you!

**Comment by chrherold** [comment]
The image processing and data acquisition tools you are asking about are part of the product sphere of Zellmechanik Dresden GmbH. 

https://www.zellmechanik.com/
