### ISSUE TITLE
Changing the orders of the plots

### ISSUE THREAD

**Issue by sdespina** [DC-analysis/DCscope#46]
In Shape-out 1 the user has the option to change the order of the plots, this is not yet implemented in Shape out 2. I think it's important for having the correct layout/order in the exported svg file, especially when comparing 2 different groups with multiple repeats.

**Comment by paulmueller** [comment]
What do you think - Should the order of the plots be governed by the order of the rows in the Block Matrix, or should each plot have its own ordering options (the latter is more difficult to implement)?

**Comment by sdespina** [comment]
If one could move the order in the Block Matrix then I think this should suffice

**Comment by felix-r** [comment]
After some time I wanted to create plots simply from ShapeOut2 and have to second Despina that it would be a really helpful feature. Especially if you plot with `marker hue = Dataset`, where you plot the data points from different datasets on top of each other, it is useful to set the order in which the datasets should be plotted.

**Comment by paulmueller** [comment]
Thanks for your input. On second thought, I think I should give this issue higher priority.
