### ISSUE TITLE
Calculating YM from metadata

### ISSUE THREAD

**Issue by sdespina** [DC-analysis/DCscope#48]
I have noticed that some discrepancies with the viscosity values when calculating the YM from metadata. I am a bit puzzled as I expect viscosity to decrease with increasing temperature.

I was using 0.6% Methyl cellulose. 
for example: 
1. 22.1°C 6.77mPA s
2. 22.7°C 9.88mPA s
3. 22.4°C 7.76mPA s
Please see the attach screen shots

![Viscocity error shape out 2 a](https://user-images.githubusercontent.com/52213329/89545592-d9df1a00-d803-11ea-8db7-62723d23da36.PNG)
![Viscocity error shape out 2 b](https://user-images.githubusercontent.com/52213329/89545614-e06d9180-d803-11ea-8f0a-574396faf3c7.PNG)
![Viscocity error shape out 2 c](https://user-images.githubusercontent.com/52213329/89545628-e499af00-d803-11ea-924a-553af5f99fa6.PNG)

**Comment by paulmueller** [comment]
When I open a single measurement and edit the temperature, I see that the viscosity decreases with increasing temperature.
Maybe in these examples you have different channel sizes or flow rates? For CellCarrier B, the viscosity is computed according to equation 7 in https://arxiv.org/abs/1704.00572:
![image](https://user-images.githubusercontent.com/2853022/89563047-241fc580-d81b-11ea-8d08-56c04fc5e774.png)

**Comment by sdespina** [comment]
Ok thanks Paul! No this was the same size channel but you are right I have 3 different flow rates- I had a lot of conditions in this experiment and I thought it was the same flow rate but different concentration of cells (but in fact is the other way round!)
Sorry about the confusion!
