### ISSUE TITLE
Loading the datasets

### ISSUE THREAD

**Issue by sdespina** [DC-analysis/DCscope#50]
At the moment you need to load the data sets one by one by specifically clicking into each subfolder. I find this a bit tedious.
I think it's better to select one experiment folder and then all the subfolders are automatically loaded, as it is currently in Shape-Out 1.

**Comment by chrherold** [comment]
Hi. Drag and Drop of a folder should do that trick.

**Comment by paulmueller** [comment]
I think Christoph's comment is the answer to your problem. Please reopen if drag&drop does not work.

**Comment by sdespina** [comment]
> Hi. Drag and Drop of a folder should do that trick.

Thanks! I didn't know this trick
