### ISSUE TITLE
Bring to front on startup?

### ISSUE THREAD

**Issue by paulmueller** [DC-analysis/DCscope#52]
Does Shape-Out become the front and focused window when started on Windows/macOS? Please comment.

**Comment by chrherold** [comment]
macOS: Yes

Windows: No

(Version 2.2.4)

**Comment by paulmueller** [comment]
Is this behavior on Windows OK/expected for/by a regular Windows user?

**Comment by chrherold** [comment]
No, actually it is quite weird that it opens in the background and needs to be selected again to be used.

**Comment by paulmueller** [comment]
I believe that should be fixed in 2.2.5. Please reopen if this is not the case.
