### ISSUE TITLE
Event image background correction with "bg_image" feature.

### ISSUE THREAD

**Issue by paulmueller** [DC-analysis/DCscope#54]
The latest version of Shape-In can save the rolling-mean background image "image_bg" feature in the .rtdc file. The task is to implement background correction in the user interface of the QuickView window.

What you will learn as a contributor
----------------------------------------------
- edit QtDesigner files (adding a checkbox)
- connecting checkbox signals such that the displayed image event is updated on-the-fly
- editing the [QuickView](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/blob/master/shapeout2/gui/quick_view/qv_main.py#L15) class
- writing test functions for PyQt5 with pytest-qt

Tasks
--------
- [ ] In QuickView, add another check box called "Subtract background" (checked by default)
      ![image](https://user-images.githubusercontent.com/2853022/108279130-6471e000-717c-11eb-931e-60e2b15e9cca.png)
- [ ] Make that check box immediately redraw the image event when the user clicks on it
- [ ] Hide that check box, if the feature "image_bg" is not available in the current dataset
- [ ] Write test functions for all of the above

Notes
--------
- This task should be straight-forward, most of the check-box logic can be copy-pasted from existing code. However, diving into Shape-Out might require some time, so don't hesitate to ask questions.
- Use this dataset for manual verification and for testing: [2020-10_image_bg.zip](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/files/5999175/2020-10_image_bg.zip) (place the unzipped .rtdc file into the "tests/data" directory)
- Before writing tests, familiarize yourself with existing test functions and try to understand the limits (and workarounds) of automated testing with pytest-qt

**Comment by maxschloegel** [comment]
I am on my way to implement the background correction and some things I am unsure about:

1. How exactly is the background correction supposed to be implemented? What is its exact purpose?

My first idea was to subtract the background from the cell-image and then take the absolute values. Problems:
- This leads inversion of the image (background is brighter→higher pixel values)
- Pixel inside the cell that are brighter than background are not inverted and therefore we lose information about pixel-variance in cell.

I could also invert this image to counteract the implicit inversion

If the background subtraction is for combating background drift, we could also compute the difference of "image_bg" to a reference "image_bg" (e.g. from the start of the data acquisition) and subtract this shift.

Which one is the right interpretation of "background correction"?

2. When implementing to hide the CheckBox when the dataset has not feature "image_bg", my current idea is to put the corresponding code into the setter-function of the "rtdc_ds"-property. I dont see any other similarly efficient location, but it feels a bit out of place in the setter function.
Maybe I need to understand the code better to find a more suitable location.
What is your opinion on that?

Thanks!

**Comment by paulmueller** [comment]
1. Here, background correction is for visualization purposes only.
   I would not take the absolute value.
   - I did not anticipate image inversion. Maybe just subtract the background and add the mean of the background image to the entire array (Maybe this should only happen when "Auto contrast is set"?)?
   - Do you have example images? I imagine a background-corrected image to look like the original image without the channel visible (since it's only for visualization purposes).

   Here we are not dealing with background drift. This is could maybe become an ancillary feature at some point, but it is out of the scope of this issue.

2. Yes, I think the rtdc_ds.setter function would be the best candidate.

Thank You!

**Comment by maxschloegel** [comment]
Re 1: 
Only subtracting the deviation from the mean of the background image solves the issue, good idea! It removes the channel very well. Here are some example images of the original and the corrected image with and without auto contrast:

**No Background correction:**
- No Auto Contrast
![cellimg_noAC](https://user-images.githubusercontent.com/30384152/108566983-9e232200-7307-11eb-9465-3c634eb92bde.png)
- With Auto Contrast
![cellimg_AC](https://user-images.githubusercontent.com/30384152/108566976-9cf1f500-7307-11eb-921f-40446b18d977.png)

**With Background Correction:**
- No Auto Contrast
![cellimg_corrected_noAC](https://user-images.githubusercontent.com/30384152/108566981-9e232200-7307-11eb-889f-61191c220486.png)
- With Auto Contrast
![cellimg_corrected_AC](https://user-images.githubusercontent.com/30384152/108566980-9d8a8b80-7307-11eb-9ec6-70344380c35f.png)

Is this what you had in mind?

I personally would keep the choices for "Auto Contrast" and "Subtract Background" independent, as their purpose is somewhat orthogonal, but I dont have a hard opinion on that and can add this condition.

Re 2: Ok, will do that!

**Comment by paulmueller** [comment]
:+1: Sounds all good to me!

**Comment by paulmueller** [comment]
fixed in https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/pull/78
