### ISSUE TITLE
Assign temperature manually to multiple measurements

### ISSUE THREAD

**Issue by MartinKrater** [DC-analysis/DCscope#60]
If temperature wasn´t recorded during a measurement, I´d like to assign the same temperature to multiple measurments in order to calculate YM. Currently, it´s only possible one by one.

**Comment by paulmueller** [comment]
I implemented this in 87a119f9306665bb500e2f9f920967c0ddc4b7f2.

You can find this feature in the "Bulk Action" menu. Could you please test it thoroughly (try to break things) and let me know whether it works as expected?

Development version download for Windows:
https://ci.appveyor.com/project/paulmueller/shapeout2/builds/36405730/artifacts

Todo:

- [x] update documentation
- [x] write test functions
