### ISSUE TITLE
Cut axis labels when exporting subplot as PNG

### ISSUE THREAD

**Issue by chrherold** [DC-analysis/DCscope#7]
Axis label are cut when a subplot is exported as PNG file. 

Example below, red Arrows indicate a cut of part of the panel to the left on the left side and the cut off label of this plot on the right side. SVG export works correctly though.

![exp1](https://user-images.githubusercontent.com/13899168/70054243-6da67980-15d7-11ea-8b03-fb2cf4510ae8.png)

**Comment by chrherold** [comment]
Additional remark: Ideally, every exported subplot should also present the names of x and y axis. Further use would otherwise be limited.

**Comment by paulmueller** [comment]
I guess it would make sense to then create a completely new plot in the background with
- [x] title
- [x] axes labels
- [x] same (or at least similar) size / aspect ratio

... and export that.

**Comment by chrherold** [comment]
Seems very reasonable, yes. At least in case of subplot export.

**Comment by paulmueller** [comment]
Please check whether this is resolved in https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/releases/tag/2.0.0b12

EDIT: It's not, sorry.

**Comment by paulmueller** [comment]
But it should be in b13
