### ISSUE TITLE
Window doesn't scale to show all graphs

### ISSUE THREAD

**Issue by marketakub** [DC-analysis/DCscope#72]
Using version 2.4.15
Supposed to have 4 columns, you can't see the right side:
![image](https://user-images.githubusercontent.com/46028267/105044612-3909b180-5a67-11eb-8cda-b2a101b59379.png)

**Comment by paulmueller** [comment]
Does this go away if the plot titles are shorter? If yes, then the fix for #33 and #63 should also include this case here.

**Comment by paulmueller** [comment]
Could you please check whether this is fixed with #33. Here is the Windows installer for the development version: https://ci.appveyor.com/project/paulmueller/shapeout2/builds/37925366/artifacts

**Comment by paulmueller** [comment]
Please reopen if this is not fixed in 2.6.0.
