### ISSUE TITLE
Preferences unavailable in OSX .app version

### ISSUE THREAD

**Issue by chrherold** [DC-analysis/DCscope#76]
Likely for similar reason as issue #73 ?
Trying to open preferences on OSX .app version yields the following error message:

> Unhandled exception in Shape-Out version 2.5.0:
> Traceback (most recent call last):
>   File "shapeout2/gui/main.py", line 648, in on_action_preferences
>   File "shapeout2/gui/preferences.py", line 24, in __init__
>   File "dclab/lme4/rsetup.py", line 130, in has_r
>   File "dclab/lme4/rlibs.py", line 23, in __getattr__
> ImportError: Please install 'rpy2>=2.9.4'!
> 

Expectation: Should work regardless of an available version of R

**Comment by paulmueller** [comment]
No, not related to #73, I just missed a case.
