### ISSUE TITLE
Shape-Out 2.6.2 fail to install 

### ISSUE THREAD

**Issue by sdespina** [DC-analysis/DCscope#84]
After installation, an error message pops up: 'Failed to execute script'
![Failed to execute](https://user-images.githubusercontent.com/52213329/114069545-65331280-989f-11eb-94e3-2414fc7f7e32.PNG)

**Comment by paulmueller** [comment]
Thanks! I pinned this down to a new release of rpy2 3.4.3.

**Comment by paulmueller** [comment]
https://github.com/rpy2/rpy2/issues/796
