### ISSUE TITLE
Support dclab plugin and ml features in Shape-Out2

### ISSUE THREAD

**Issue by PinkShnack** [DC-analysis/DCscope#85]
Plugin features are a way for users to define their own features within dclab. The original dclab issue is [here](https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/105) and the soon to be merged PR is [here](https://github.com/ZELLMECHANIK-DRESDEN/dclab/pull/113).

These should be available in Shape-Out2.

**Comment by maikherbig** [comment]
I would be highly interested in that feature!!!

**Comment by paulmueller** [comment]
Thanks! We are currently very busy with other projects, so don't expect this to be implemented within the next month.

**Comment by paulmueller** [comment]
Before this can be implemented, we need https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/144 and https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/143.

**Comment by paulmueller** [comment]
TODO:

- [x] tests
- [x] docs
- ~include tensorflow in builds~ (not for now)

**Comment by paulmueller** [comment]
See https://shapeout2.readthedocs.io/en/stable/sec_qg_extensions.html

**Comment by PinkShnack** [comment]
Fantastic! Thanks for doing this Paul!
