### ISSUE TITLE
Open session files by double click

### ISSUE THREAD

**Issue by phidahl** [DC-analysis/DCscope#88]
Many programs are linked to certain file types in the os, so that double clicking a document files for example opens libreoffice with the clicked document. This intuitively integrates a program into a user's workflow.

Would that be possible for ShapeOut, too? - I think the implementation might differ on the platforms, but Windows should be most common and have highest priority.

Alternatively or additionally drag & drop of session files could open the session. Dropping data files is working on all platforms which is already very handy.

**Comment by paulmueller** [comment]
Yes, that would have to be done in the InnoSetup configuration file: https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/blob/master/build-recipes/win_shapeout2.iss_dummy

**Comment by paulmueller** [comment]
Fixed by the commits above.
