### ISSUE TITLE
Add autoscale check box to Plotsettings

### ISSUE THREAD

**Issue by chrherold** [DC-analysis/DCscope#9]
Currently automated plot range dependent on min/max values is only suggested when changing variables of x or y axis in the 'General' field of Plot in Analysis View. A check box initially set checked for autoscaling would be desirable. If checked scaling of plots should be updated when a plot is added or a filter setting is changed. If unchecked, the settings given in the spin boxes should be maintained.

I guess it would also be desirable to not have min/max events on/below the plot axes. Therefore, slightly a larger plot range compared to min/max should be set. I would suggest an added ±5% of the min-max range.

**Comment by paulmueller** [comment]
...and if the user touches the range controls, the checkbox should automatically uncheck itself (and the other way around should also work).
