### ISSUE TITLE
Duplicating a dataset does not keep the name

### ISSUE THREAD

**Issue by B-Hartmann** [DC-analysis/DCscope#96]
Shape-Out 2.6.8
Windows 10

I had several datasets loaded in a session, renamed them and gave them custom colors. In the block matrix, I clicked on "duplicate" to insert a dataset again. The name and the color were not copied. I expected that the "duplicate" function would copy the name (and color), while the "insert anew" function would insert just the plain dataset.
In the Analysis View, I found the two options "duplicate this dataset without custom options" and "duplicate this dataset", and the latter one seems to keep at least the color, althought the name was still changed to the default name.

In my opinion, for consistency, it would make sense if the two options in the Analysis View (in the dataset tab) were the same as the two options in the block matrix. 
At least the name should be kept in all "duplicate" functions.

**Comment by paulmueller** [comment]
I think there was some reason why I specifically set the name and color of the original dataset. But I did not justify it in the sources and your reasoning makes a lot of sense to me.
